### ISSUE TITLE
[Android] Chức năng ngắn hoàn thành trong 2 tuần.

### ISSUE THREAD

**Issue by chien-pro** [chien-pro/Geek1Project#2]
1, Đọc báo Offline 
2, Help (có bàn tay chỉ)
3, Bỏ chọn furiType => show favorite list on float button.
4, Thêm chức năng ẩn/hiện furigana trong float button.
5, Fix bug đơ app ở màn hình Setting
6, Night mode setting.
7, Rate app in Setting Screen.
8, Fix lỗi quảng cáo

**Comment by toannv53** [comment]
đọc báo offline chắc là không ổn lắm. t check lại phía android thì có lẽ cần phải thiết kế lại phần đó. Nên thời gian có lẽ lâu hơn 2 tuần.

>5, Fix bug đơ app ở màn hình Setting

hiện tượng bị làm sao nhỉ?

**Comment by chien-pro** [comment]
5, bug đơ app setting : Tưởng m fix rồi ?
E dùng android ạ
lybk.rec@gmail.com ạ
E cứ vào phần cài đặt thì bị báo là dừng lại
Quay về trang chủ
![aaa](https://user-images.githubusercontent.com/1861174/38792720-70e458f2-4189-11e8-92e6-9f4de2a1233e.jpg)

1, đọc báo offline:
- T đang lưu vào 2 file Json (1 json main & 1 json 20 detail) vào 2 file
- Khi reload main thì update file.
- Tổng tất cả các báo chi lưu 20 bài ( ko phân biệt Category).
